version: '3.7'
services:
  app:
    container_name: react-wallet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./app
      target: /home/wallet/app
    command: /bin/sh
    ports:
      - 3000:3000
    stdin_open: true
    tty: true